# DigitalTwinAgent Configuration File
[project]
name = "DigitalTwinAgent"
description = "Agent responsible for logging, error handling, and bug identification."
version = "0.1.0"

[dependencies]
python = "^3.8"
autogen = "^1.0.0"

[agent]
api_key = os.getenv("DT_API_KEY")
model_path = "models/dt_model"
training_data_path = "data/dt_training_data.csv"

[logging]
log_level = "INFO"
log_format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
log_file = "logs/dt.log"

[security]
encryption_key = os.getenv("DT_ENCRYPTION_KEY")
token_expiry = 3600

[validation]
required_keys = ["agent.api_key", "security.encryption_key"]
