version: '3.8'
services:
  ecobot-app:
    image: ecobot:latest
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecobot_db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
