# Dockerfile.ecobot

FROM python:3.8-slim

# Set the working directory in the container to root
WORKDIR /

# Copy the requirements file into the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container
COPY . .

# Make port 8501 available to the world outside this container
EXPOSE 8501

# Define the command to run the app
CMD ["streamlit", "run", "streamlit_app/Eco-BotAPP.py"]
