version: '3.8'

services:
  eco-bot:
    image: eco-bot:latest
    build: 
      context: .
      dockerfile: Dockerfile.ecobot
    environment:
      - SOME_ENV_VAR=value
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Add any additional services here
  gma:
    image: gma:latest
    build:
      context: .
      dockerfile: Dockerfile.gma
    environment:
      - GMA_ENV_VAR=value
    volumes:
      - ./logs:./agents/log/gma.log
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      - eco-bot

  # Add any additional services here
  dt:
    image: dt:latest
    build:
      context: .
      dockerfile: Dockerfile.dt
    volumes:
      - ./logs:/agents/log/dt.log
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      - gma

volumes:
  logs:
networks:
  internal:
