# Eco-Bot Configuration File
[project]
name = "Eco-Bot"
description = "A bot designed to assist users in making eco-friendly choices."
version = "0.1.0"

[dependencies]
python = "^3.8"
autogen = "^1.0.0"
tensorflow = "^2.6.0"
numpy = "^1.21.0"

[autogen]
# Configuration for the AutoGen tool integration
api_key = "YOUR_ENV_VARIABLE"  # Replace with your environment variable for AutoGen API key
model_path = "models/autogen_model"
training_data_path = "data/training_data.csv"

[bot]
# OpenAI API credentials
openai_api_key = "YOUR_ENV_VARIABLE_FOR_OPENAI_KEY"

# Path to Eco-Bot personality script
personality_script_path = "scripts/eco_bot_personality.txt"

# Path to system messages
system_message_path = "messages/system_messages.json"

# (Future) Computer Vision Configuration
[bot.computer_vision]
# Placeholder for future computer vision configurations
model_path = "models/computer_vision_model"

[database]
# Configuration for database connections
db_name = "eco_bot_db"
db_user = "admin"
db_password = "YOUR_ENV_VARIABLE"  # Replace with your environment variable for database password
db_host = "localhost"
db_port = "5432"

[logging]
# Configuration for logging
log_level = "INFO"
log_format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
log_file = "logs/eco_bot.log"

[webserver]
# Configuration for the web server
host = "0.0.0.0"
port = "8000"

[security]
# Security configurations for the Eco-Bot
encryption_key = "YOUR_ENV_VARIABLE"  # Replace with your environment variable for encryption key
token_expiry = 3600  # in seconds
